image: Visual Studio 2019
before_build:
  - choco install codecov
build_script:
  - dotnet build
test_script:
  - dotnet test --collect:"XPlat Code Coverage"
  - ps: ./FindCoverageFile.ps1
  - codecov -f ./App.Tests/TestResults/coverage.cobertura.xml
